######################################################################
# Automatically generated by qmake (2.01a) ?? 18. ??? 17:33:47 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . \
				alglib
CONFIG += release
#QMAKE_CXXFLAGS += -O2

# Input
SOURCES += calc.cpp \
			map-parser.cpp \
			projection.cpp
